language: julia
os:
    - linux
    - osx
coveralls: true
julia:
    - 1.0
    - 1.1
    - nightly
notifications:
    email:
      on_success: change
      on_failure: always
matrix:
    allow_failures:
        - julia: nightly
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("Noise")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
